server:
  port: 4000

spring:
  application:
    name: "Day01_2"

   # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

file:
  upload:
    path: # - 는 리스트 형태의 값 - file.upload.path
      -D:/uploads/
      -D:/uploads2/
    url: /uploads/ #file.upload.url

