server:
  port: 3000

spring:
  #데이터 베이스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  #JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true #실행하는 sql을 콘솔에 출력
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

#로거설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace